
export const getRandomPlanetName = () => {
  const randomPlanetTypeIndex = Math.floor(Math.random() * planetNames.length);
  console.log({ randomPlanetTypeIndex })
  return planetNames[randomPlanetTypeIndex]
}

const planetNames = [
  "Acrisia",
  "Agartha",
  "Akatsuki",
  "Al-Jissa",
  "Al-Karak",
  "Al-Mada'in",
  "Al-Matabbah",
  "Al-Nuqayrah",
  "Albion",
  "Amor",
  "Anchor",
  "Asgard",
  "Athura",
  "Aurora",
  "Avalon",
  "Bounty",
  "Capella",
  "Concord",
  "Corregan",
  "Dawn",
  "Delgovicia",
  "Destinikon",
  "Dis",
  "Doron",
  "Durkheim",
  "Euterpe",
  "Faunus",
  "Fincastle",
  "Flaxington",
  "Gao Zu",
  "Girdwood",
  "Grinstead",
  "Hesperides",
  "Hesperos",
  "Hinckley's Hope",
  "Hope",
  "Horizon",
  "Hoxworth",
  "Keresia",
  "Knutton",
  "Kongzi",
  "La Isabela",
  "Las Veredas",
  "Leffingwell",
  "Melpomenia",
  "Mullineux",
  "New Coventry",
  "New Jamestown",
  "New Jerusalem",
  "New Roanoke",
  "New Troy",
  "Nexon",
  "Noricum",
  "Nova Constantinople",
  "Nozomi",
  "Nueva Cádiz",
  "Nueva Sonora",
  "Oda",
  "Olympia",
  "Osiris",
  "Pallas",
  "Pallena",
  "Pangea",
  "Port Karakosov",
  "Proclas",
  "Puerto González",
  "Rama",
  "Rattenbury",
  "Rhea",
  "Salaam",
  "San Cristóbal",
  "San Fernando",
  "San Lucas",
  "Saon",
  "Serendipity",
  "Smitheus",
  "Solaria",
  "Soma",
  "Spring",
  "St. Caspar",
  "St. Hossack",
  "St. Knatchbull",
  "St. Pomeroy",
  "St. Yegorov",
  "Tartessos",
  "Terra Nova",
  "Tethys",
  "Theia",
  "Theia",
  "Thinis",
  "Tian Yi",
  "Tokugawa",
  "Toyotomi",
  "Treadway",
  "Tronchet",
  "Truett",
  "Tuscany",
  "Tyndis",
  "Vishnu",
  "Wenzhou",
  "Wu Ding",
  "Xianyang",
  "Zheng",
  "Zoroaster",
]
